apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-mysql-master-0
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql-master-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-mysql-slave-0
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql-slave-0
